<script setup lang="ts">
import { ref,computed,onMounted,onBeforeUnmount } from 'vue'
import { useRoute,onBeforeRouteLeave } from 'vue-router'
import { meetingService,type Meeting,type Segment,type Revision } from './MeetingService'
import { teamService,type Member } from '../team/TeamService'
import TranscriptionPanel from '../transcription/TranscriptionPanel.vue'
import OutcomePanel from '../outcome/OutcomePanel.vue'
import SummaryPanel from './SummaryPanel.vue'
const route=useRoute(),id=String(route.params.meeting),meeting=ref<Meeting|null>(null),segments=ref<Segment[]>([]),members=ref<Member[]>([]),history=ref<Revision[]>([])
const version=ref(0),saved=ref('[]'),active=ref(false),approved=ref(false),busy=ref(false),error=ref(''),notice=ref(''),historyText=ref('')
const dirty=computed(()=>JSON.stringify(segments.value)!==saved.value)
onMounted(async()=>{try{meeting.value=await meetingService.get(id);const [transcript,people,versions]=await Promise.all([meetingService.transcript(id),teamService.members(meeting.value.teamId),meetingService.history(id)]);segments.value=transcript.segments;version.value=transcript.version;saved.value=JSON.stringify(segments.value);members.value=people;history.value=versions}catch(e){error.value=(e as Error).message}})
async function save(){if(!approved.value||active.value)return;busy.value=true;error.value='';notice.value='';try{const result=await meetingService.save(id,version.value,segments.value);version.value=result.version;saved.value=JSON.stringify(segments.value);approved.value=false;history.value=await meetingService.history(id);notice.value=`기록 v${version.value}을 저장했습니다.`}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function end(){if(active.value||dirty.value)return;if(!window.confirm('이 회의를 종료할까요? 저장한 기록과 산출물은 다시 열 수 있습니다.'))return;busy.value=true;try{meeting.value=await meetingService.end(id)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function preview(v:number){try{const t=await meetingService.transcript(id,v);historyText.value=t.segments.map(s=>s.text).join('\n\n')}catch(e){error.value=(e as Error).message}}
function download(){const blob=new Blob([segments.value.map(s=>`[${new Date(s.receivedAt).toLocaleTimeString('ko-KR')}] ${s.text}`).join('\n\n')],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='meeting-transcript.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function beforeUnload(e:BeforeUnloadEvent){if(dirty.value||active.value)e.preventDefault()}
onMounted(()=>window.addEventListener('beforeunload',beforeUnload));onBeforeUnmount(()=>window.removeEventListener('beforeunload',beforeUnload))
onBeforeRouteLeave(()=>{if((dirty.value||active.value)&&!window.confirm('이동하면 음성 입력이 중지되고 저장하지 않은 기록은 사라집니다. 이동할까요?'))return false})
</script>
<template><section><p v-if="error" role="alert" class="notice error">{{error}}</p><template v-if="meeting"><RouterLink class="back" :to="`/teams/${meeting.teamId}`">← 팀 회의</RouterLink><div class="section-head"><div><h1>{{meeting.title}}</h1><p>{{meeting.status==='OPEN'?'회의 진행 가능':'종료된 회의'}} · 저장 기록 v{{version}} · {{dirty?'저장하지 않은 변경 있음':'저장 내용과 일치'}}</p></div><button v-if="meeting.status==='OPEN'" class="secondary" :disabled="busy||active||dirty" @click="end">회의 종료</button></div><p v-if="active||dirty" class="muted">회의를 종료하려면 입력을 중지하고 변경한 기록을 저장하세요.</p><p v-if="notice" role="status" class="notice">{{notice}}</p><div class="meeting-layout"><div><TranscriptionPanel v-model="segments" :disabled="busy||meeting.status==='ENDED'" @active="active=$event"/><div class="save-bar"><label class="check"><input v-model="approved" type="checkbox" :disabled="busy||active">원문을 검토했으며 팀원에게 공유되는 서버 저장에 동의합니다. 저장 버전과 승인 이력이 남습니다.</label><div class="actions"><button :disabled="busy||active||!approved||!dirty" @click="save">검토 완료 · 전사 저장</button><button class="secondary" :disabled="!segments.length" @click="download">내 기록 TXT 받기</button></div><p class="record-note">음성 파일은 저장하지 않습니다. 브라우저를 닫기 전 저장하거나 TXT로 받아 주세요. 원문 저장을 원하지 않으면 TXT만 내려받고 페이지를 나갈 수 있습니다.</p></div><details v-if="history.length" style="margin-top:32px"><summary>저장 이력 · {{history.length}}개 버전</summary><ul><li v-for="h in history" :key="h.version"><button class="text-button" @click="preview(h.version)">v{{h.version}} · {{new Date(h.createdAt).toLocaleString('ko-KR')}}</button></li></ul><pre style="white-space:pre-wrap;overflow-wrap:anywhere">{{historyText}}</pre></details></div><aside><SummaryPanel :meeting="id" :version="version" :dirty="dirty"/><OutcomePanel :meeting="id" :members="members"/></aside></div></template><p v-else-if="!error">회의를 불러오는 중입니다.</p></section></template>
