<script setup lang="ts">
import { ref,onMounted } from 'vue'
import { outcomeService,type Outcome } from './OutcomeService'
import type { Member } from '../team/TeamService'
const props=defineProps<{meeting:string;members:Member[]}>(),items=ref<Outcome[]>([]),kind=ref('DECISION'),text=ref(''),owner=ref(''),due=ref(''),approved=ref(false),busy=ref(false),error=ref('')
const labels={DECISION:'결정사항',ACTION:'할 일',ISSUE:'미결 쟁점'}
onMounted(()=>outcomeService.list(props.meeting).then(v=>items.value=v).catch(e=>error.value=e.message))
async function save(){busy.value=true;error.value='';try{await outcomeService.create(props.meeting,{kind:kind.value,text:text.value,ownerId:kind.value==='ACTION'?owner.value||null:null,dueDate:kind.value==='ACTION'?due.value||null:null});items.value=await outcomeService.list(props.meeting);text.value='';owner.value='';due.value='';approved.value=false}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function status(item:Outcome,value:string){busy.value=true;try{items.value=await outcomeService.status(props.meeting,item,value)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
</script>
<template><section><h2>회의에서 남길 것</h2><p class="muted">사람이 확인한 결정과 다음 행동을 작성합니다. 미정인 담당자와 기한은 비워 두세요.</p><p v-if="error" role="alert" class="notice error">{{error}}</p><form @submit.prevent="save"><label>기록 종류<select v-model="kind" aria-label="기록 종류"><option value="DECISION">결정사항</option><option value="ACTION">할 일</option><option value="ISSUE">미결 쟁점</option></select></label><label>내용<textarea v-model="text" aria-label="산출물 내용" required maxlength="2000" rows="3"/></label><template v-if="kind==='ACTION'"><label>담당자<select v-model="owner" aria-label="담당자"><option value="">미정</option><option v-for="m in members" :key="m.id" :value="m.id">{{m.name}}</option></select></label><label>기한<input v-model="due" type="date"></label></template><label class="check"><input v-model="approved" type="checkbox" required>내용을 검토했으며 팀에 공유합니다.</label><button :disabled="busy||!approved||!text.trim()">검토 완료 · 저장</button></form><ul class="task-list"><li v-for="item in items" :key="item.id"><strong>{{labels[item.kind]}}</strong><p>{{item.text}}</p><template v-if="item.kind==='ACTION'"><small>{{members.find(m=>m.id===item.ownerId)?.name||'담당자 미정'}} · {{item.dueDate||'기한 미정'}}</small><label>진행 상태<select :value="item.status" :disabled="busy" :aria-label="`${item.text} 진행 상태`" @change="status(item,($event.target as HTMLSelectElement).value)"><option value="TODO">할 일</option><option value="DOING">진행 중</option><option value="DONE">완료</option></select></label></template></li></ul></section></template>
