server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  servlet:
    session:
      cookie:
        secure: true
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
